image: composer:2.5.5

definitions:
  services:
    pgsql:
      image: postgres:13-alpine
      environment:
        POSTGRES_DB: 'medical'
        POSTGRES_USER: 'user'
        POSTGRES_PASSWORD: '123'
  steps:
    - step: &testin-app
        name: Testing app
        script:
          - ln -f -s .env.example .env
          - composer install --ignore-platform-reqs
          - php artisan key:generate
          - php artisan jwt:secret
          - php artisan test
        services:
          - pgsql
    - step: &syntax-test
        name: syntax test
        script:
          - ./vendor/bin/pint --test
          - ./vendor/bin/phpcs

pipelines:
  default:
      - stage:
          name: Test app
          steps:
              - step: *testin-app
              - step: *syntax-test
  branches:
    master:
      - stage:
          name: Test app
          steps:
              - step: *testin-app
              - step: *syntax-test
      - step:
          name: Run Deployment Trigger
          script:
            - echo "no deployment trigger set"
      - step:
          name: Test success deployment
          deployment: staging
          script:
            - echo "todo: test success deployment"
    v100:
      - stage:
          name: Test app
          steps:
              - step: *testin-app
              - step: *syntax-test
      - step:
          name: Run Deployment Trigger
          script:
            - curl -vk https://forge.laravel.com/servers/675028/sites/1962572/deploy/http?token=K06EZkQmi3CeSRtLbGnS8v7jc85bkneyXYLnvDZP
    staging:
      - stage:
          name: Test app
          steps:
              - step: *testin-app
              - step: *syntax-test
      - step:
          name: Run Deployment Trigger
          script:
            - curl -vk https://forge.laravel.com/servers/675028/sites/1957954/deploy/http?token=rE2fyLL6v4TDMJSlDG84jKewgQnD4hr4FV5rP03x
