image: composer:2.5.5

definitions:
  services:
    pgsql:
      image: postgres:13-alpine
      environment:
        POSTGRES_DB: $DB_DATABASE
        POSTGRES_USER: $DB_USERNAME
        POSTGRES_PASSWORD: $DB_PASSWORD
  steps:
    - step: &testin-app
        name: Testing app
        image: pawelgradziel/php82-cli-xdebug-composer:latest
        script:
          - ln -f -s .env.testing .env
          - composer install --ignore-platform-reqs
          - php artisan key:generate
          - php artisan jwt:secret
          ## - php artisan test -p --coverage-clover --configuration phpunit.xml --min=$COVERAGE_MIN
          - ./vendor/bin/phpunit --log-junit ./test-reports/phpunit.junit.xml --coverage-clover ./test-reports/phpunit.coverage.xml
        services:
          - pgsql
        caches:
          - composer
    - step: &syntax-test
        name: syntax test
        script:
          - ln -f -s .env.example .env
          - composer install --ignore-platform-reqs
          - ./vendor/bin/pint --test
          ## - ./vendor/bin/phpcs
          ## - ./vendor/bin/pstan
        caches:
          - composer
    - step: &deploy-forge
          name: Run Forge Quik Deployment
          deployment: Test
          script:
            - curl -vk https://forge.laravel.com/servers/$SERVER_ID/sites/$SERVER_SITE/deploy/http?token=$DEPLOY_TOKEN

pipelines:
  default:
      - stage:
          name: Test app
          steps:
              - step: *testin-app
              - step: *syntax-test
  branches:
    master:
      - stage:
          name: Test app
          steps:
              - step: *testin-app
              - step: *syntax-test
      - step:
          <<: *deploy-forge
          deployment: Production
      - step:
          name: Test success deployment
          deployment: staging
          script:
            - echo "todo: test success deployment"
    v100:
      - stage:
          name: Test app
          steps:
              - step: *testin-app
              - step: *syntax-test
      - step:
          <<: *deploy-forge
          deployment: V100
    staging:
      - stage:
          name: Test app
          steps:
              - step: *testin-app
              - step: *syntax-test
      - step:
          <<: *deploy-forge
          deployment: Staging
