image: php:8.2.9

definitions:
  caches:
    vendor: vendor
  services:
    pgsql:
      image: postgres:14-alpine
      environment:
        POSTGRES_DB: $DB_DATABASE
        POSTGRES_USER: $DB_USERNAME
        POSTGRES_PASSWORD: $DB_PASSWORD
  steps:
    - build: &build
        name: Build app
        caches:
          - composer
          - vendor
        script:
          - ln -f -s .env.example .env
          - apt-get update && apt-get install -y gnupg gosu curl zip unzip supervisor libcap2-bin libpng-dev dnsutils libcurl4-openssl-dev libmcrypt-dev libzip-dev libicu-dev && apt-get clean
          - docker-php-ext-install gd curl zip bcmath intl
          - curl -sLS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer
          - composer install --no-interaction --prefer-dist
        services:
          - pgsql
    - step: &testin-app
        name: Testing app
        caches:
          - composer
          - vendor
        script:
          - ln -f -s .env.testing .env
          - apt-get update && apt-get install -y libpq-dev postgresql-client && apt-get clean
          - docker-php-ext-install pgsql pdo_pgsql
          - XDEBUG_MODE=debug,coverage
          - php artisan key:generate
          - php artisan jwt:secret
          - php artisan migrate
          - php artisan serve &
          - sleep 5
          - php -v
          - php artisan test #--coverage --min=$COVERAGE_MIN
        variables:
          XDEBUG_MODE: debug,coverage
        services:
          - pgsql
    - step: &syntax-test
        name: syntax test
        caches:
          - composer
          - vendor
        script:
          - ln -f -s .env.example .env
          - ./vendor/bin/pint --test --config pint.json -vvv
          ## - ./vendor/bin/phpcs
          ## - ./vendor/bin/pstan
    - step: &deploy-forge
          name: Run Forge Quik Deployment
          deployment: Test
          script:
            - curl -vk https://forge.laravel.com/servers/$SERVER_ID/sites/$SERVER_SITE/deploy/http?token=$DEPLOY_TOKEN

pipelines:
  default:
      - stage:
          name: Test app
          steps:
              - step: *build
              - step: *testin-app
              - step: *syntax-test
  branches:
    master:
      - stage:
          name: Test app
          steps:
              - step: *build
              - step: *testin-app
              - step: *syntax-test
      - step:
          <<: *deploy-forge
          deployment: Production
      - step:
          name: Test success deployment
          script:
            - echo "todo test success deployment"
    v100:
      - stage:
          name: Test app
          steps:
              - step: *build
              - step: *testin-app
              - step: *syntax-test
      - step:
          <<: *deploy-forge
          deployment: V100
    v101:
      - stage:
          name: Test app
          steps:
              - step: *build
              - step: *testin-app
              - step: *syntax-test
      - step:
          <<: *deploy-forge
          deployment: V101
    staging:
      - stage:
          name: Test app
          steps:
              - step: *build
              - step: *testin-app
              - step: *syntax-test
      - step:
          <<: *deploy-forge
          deployment: Staging
