image: composer:2.5.8

definitions:
  caches:
    vendor: vendor
  services:
    pgsql:
      image: postgres:13-alpine
      environment:
        POSTGRES_DB: $DB_DATABASE
        POSTGRES_USER: $DB_USERNAME
        POSTGRES_PASSWORD: $DB_PASSWORD
  steps:
    - build: &build
        name: Build app
        caches:
          - composer
          - vendor
        script:
          - ln -f -s .env.example .env
          - composer install --ignore-platform-reqs
          - php artisan key:generate
          - php artisan jwt:secret
          - XDEBUG_MODE=coverage
    - step: &testin-app
        name: Testing app
        caches:
          - composer
          - vendor
        script:
          ## - php artisan test -p --coverage-clover --configuration phpunit.xml --min=$COVERAGE_MIN
          - ./vendor/bin/phpunit --log-junit ./test-reports/phpunit.junit.xml --coverage-clover ./test-reports/phpunit.coverage.xml
        services:
          - pgsql
    - step: &syntax-test
        name: syntax test
        caches:
          - composer
          - vendor
        script:
          - ln -f -s .env.example .env
          - composer install --ignore-platform-reqs
          - ./vendor/bin/pint --test
          ## - ./vendor/bin/phpcs
          ## - ./vendor/bin/pstan
    - step: &deploy-forge
          name: Run Forge Quik Deployment
          deployment: Test
          script:
            - curl -vk https://forge.laravel.com/servers/$SERVER_ID/sites/$SERVER_SITE/deploy/http?token=$DEPLOY_TOKEN

pipelines:
  default:
      - stage:
          name: Test app
          caches:
            - composer
            - vendor
          steps:
              - step: *build
              - step: *testin-app
              - step: *syntax-test
  branches:
    master:
      - stage:
          name: Test app
          steps:
              - step: *testin-app
              - step: *syntax-test
      - step:
          <<: *deploy-forge
          deployment: Production
      - step:
          name: Test success deployment
          deployment: staging
          script:
            - echo "todo: test success deployment"
    v100:
      - stage:
          name: Test app
          steps:
              - step: *testin-app
              - step: *syntax-test
      - step:
          <<: *deploy-forge
          deployment: V100
    staging:
      - stage:
          name: Test app
          steps:
              - step: *testin-app
              - step: *syntax-test
      - step:
          <<: *deploy-forge
          deployment: Staging
