image: composer:2.5.5

pipelines:
  default:
      - step:
          name: Build environment
          script:
            - ln -f -s .env.example .env
            - composer install --ignore-platform-reqs
            - php artisan key:generate
            - php artisan jwt:secret
          caches:
            - composer
          services:
            - pgsql
      - parallel:
          - step:
              name: Test
              script:
                - ln -f -s .env.example .env
                - composer install --ignore-platform-reqs
                - php artisan key:generate
                - php artisan jwt:secret
                - php artisan test
              caches:
                - composer
              services:
                - pgsql
          - step:
              name: syntax test
              script:
                - echo 'todo:run test'
                #- ./vendor/bin/pint --test
                #- ./vendor/bin/phpcs
              caches:
                - composer

  branches:
    master:
      - step:
          name: Deploy
          deployment: production
          script:
            - composer install --no-dev
            - php artisan migrate --force
          caches:
            - composer
    v100:
      - step:
          name: Deploy
          deployment: version
          script:
            - composer install --no-dev
            - php artisan migrate --force
          caches:
            - composer
    staging:
      - step:
          name: Deploy
          deployment: staging
          script:
            - curl -vk https://forge.laravel.com/servers/675028/sites/1957954/deploy/http?token=rE2fyLL6v4TDMJSlDG84jKewgQnD4hr4FV5rP03x
          caches:
            - composer
    forge-integration:
      - step:
          name: Deploy
          deployment: testing
          script:
            - curl -vk https://forge.laravel.com/servers/675028/sites/1957954/deploy/http?token=rE2fyLL6v4TDMJSlDG84jKewgQnD4hr4FV5rP03x
          caches:
            - composer
definitions:
  services:
    pgsql:
      image: postgres:13-alpine
      environment:
        POSTGRES_DB: 'medical'
        POSTGRES_USER: 'user'
        POSTGRES_PASSWORD: '123'